### ISSUE TITLE
Validators self-delegate is over 100%

### ISSUE THREAD

**Issue by RiccardoM** [forbole/big-dipper-desmos#32]
Currently some validators are showing more than 100% self delegate percentages: 

![screenshot-morpheus desmos network-2021 04 28-09_53_12](https://user-images.githubusercontent.com/9119016/116367564-c5b2d100-a807-11eb-9d6c-e50a7808ccc6.png)

**Comment by ryuash** [comment]
@RiccardoM This might actually be an issue with bdjuno

Ex for blockscape `desmosvalcons1d8ld00spt08rrfgnarar6kp6hwafwy2urnhs2l` their voting power is at `119804` on height `15437`

![image](https://user-images.githubusercontent.com/42913823/116415615-2b38a900-a86c-11eb-87f9-782b12bbfe88.png)

And their delegations is `119823743001 udaric` on height `15442` and `119809870260` on height `15436` we didn't have a record for height `15437`
![image](https://user-images.githubusercontent.com/42913823/116415792-53280c80-a86c-11eb-828b-927483847130.png)

even if they were both at height `119804`
Voting power `119804` and delegations `119809870260 udaric`would've surpassed 100%.

What i can do is check if the percentage is over `100%` i will just display the following as `100%` instead.

**Comment by ryuash** [comment]
update:
I'll just calculate within the delegations module. should be able to get 100%
