### ISSUE TITLE
Not fetching desmos profiles txs

### ISSUE THREAD

**Issue by bragaz** [forbole/big-dipper-desmos#54]
## Bug description
It looks like BDjuno can't fetch desmos `profiles` txs.
I've made two but I can't see them on BD.
One is inside this block: https://morpheus.desmos.network/blocks/14760.
as you can see from the block's info there are 2 txs, one is a `profiles`.
It looks like if you make a profiles' tx BD doesn't show other txs even.
If you search for its hash `9F1AB042066D6E89624BCB58936D9EDD23140910D3EFB64A321644E8416C7910` BD shows nothing.

## Steps to reproduce
perform one of the desmos `profiles` txs.
search it inside the explorer. 

## Expected behavior
`Profiles` Txs should be displayed as the cosmos ones.

**Comment by ryuash** [comment]
@RiccardoM hmm This seems more of a bdjuno issue. If it exists in bdjuno big dipper will naturally display it regardless of tx type

![image](https://user-images.githubusercontent.com/42913823/116777231-088ed600-aaa0-11eb-8b86-76b775a463e3.png)

**Comment by ryuash** [comment]
closing cause it logs.
