### ISSUE TITLE
Validator link does not open URL in new page

### ISSUE THREAD

**Issue by RiccardoM** [forbole/big-dipper-desmos#88]
Currently when clicking the validator "Website" URL, the link is not opened as an URL but it redirects you to the `/validators/{url}` page instead.

**Comment by ryuash** [comment]
@RiccardoM can you show me a validator whose website doesn't work? Their formatting might be wrong

**Comment by RiccardoM** [comment]
@ryuash https://morpheus.desmos.network/validators/desmosvaloper13m5ka6398geahrmhdlts0rxdmna6qnmtal6dnj
